name: Screenshot tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: 'gradle'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      # Download screenshots from main branch
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: screenshots
          path: app/screenshots
          workflow: screenshot_test.yaml
          branch: main

      - name: verify test
        id: verify-test
        run: |
          # If there is a difference between the screenshots, the test will fail.
          ./gradlew app:verifyRoborazziDebug --stacktrace

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: app/screenshots
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-reports
          path: app/screenshots/reports
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: app/screenshots/test-results
          retention-days: 30
